baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Yung-Hsuan's Website
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5
        - name: Tutoring Portfolio
          url: portfolio/
          weight: 1
        - name: 高中學習歷程檔案
          url: hs_portfolio/
          weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts CHANG Yung-Hsuan's curriculum vitae, contact information, and academic backgrounds."
    author: CHANG Yung-Hsuan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    # MainSections: ["portfolio"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: false
    ShowWordCount: false
    UseHugoToc: false
    comments: false
    math: true
    footer:
        text: "<em>On dirige ce qu'on affronte. C'est là qu'on trouve la magie.</em>"
        hideCopyright: true
    profileMode:
          enabled: true
          title: CHANG Yung-Hsuan (張永璿)
          subtitle: |
            &nbsp;

            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I'm Yung-Hsuan, also known as Eiken, from Hsinchu, Taiwan. I am finishing my undergraduate studies at the Department of Applied Mathematics, National Yang Ming Chiao Tung University and preparing for the next chapter in my life. I will be studying actuarial science in graduate school in the United States. I am also look forward to becoming an FSA before my 30s.

            &nbsp;
          imageUrl: "cag.jpeg"
          imageWidth: 160
          imageHeight: auto
          buttons:
            # - name: Papers
            #   url: papers/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            - name: Tutoring Portfolio
              url: portfolio/
            - name: 高中學習歷程檔案
              url: hs_portfolio/
            - name: Undergraduate Course Reflections
              url: undergraduate_course_reflections/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: eiken59_CV.pdf
        - name: Email
          url: mailto:eiken59@icloud.com
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/eiken59/
        - name: LinkedIn
          url: https://www.linkedin.com/in/eiken59/
        # - name: Google Sites
        #   url: https://sites.google.com/view/eiken59/
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
        favicon: fairy_noBG.ico
        favicon16x16: fairy-16x16.png
        favicon32x32: fairy-32x32.png
        apple_touch_icon: fairy_noBG.png
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "CHANG Yung-Hsuan"
      icon: fairy_noBG.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: true
        startLevel: 2